// Package provider implements the Terraform provider for updown.io.
package provider

import (
	"fmt"

	"github.com/Nastaliss/terraform-provider-updown/internal/updown"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func statusPageResource() *schema.Resource {
	return &schema.Resource{
		Description: "`updown_status_page` defines a status page",

		Create: statusPageCreate,
		Read:   statusPageRead,
		Update: statusPageUpdate,
		Delete: statusPageDelete,
		Exists: statusPageExists,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},

		Schema: map[string]*schema.Schema{
			"checks": {
				Type:        schema.TypeList,
				Required:    true,
				Description: "Ordered list of check tokens to display on the status page.",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			"name": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Name of the status page.",
			},
			"description": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Description of the status page.",
			},
			"visibility": {
				Type:         schema.TypeString,
				Optional:     true,
				Default:      "public",
				Description:  "Visibility of the status page (public, protected, or private).",
				ValidateFunc: validation.StringInSlice([]string{"public", "protected", "private"}, false),
			},
			"access_key": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Sensitive:   true,
				Description: "Access key for protected status pages. Auto-generated by the API.",
			},
			"url": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Public URL of the status page.",
			},
		},
	}
}

func constructStatusPagePayload(d *schema.ResourceData) updown.StatusPageItem {
	payload := updown.StatusPageItem{}

	if v, ok := d.GetOk("name"); ok {
		payload.Name = v.(string)
	}

	if v, ok := d.GetOk("description"); ok {
		payload.Description = v.(string)
	}

	if v, ok := d.GetOk("visibility"); ok {
		payload.Visibility = v.(string)
	}

	checksRaw := d.Get("checks").([]interface{})
	checks := make([]string, len(checksRaw))
	for i, v := range checksRaw {
		checks[i] = v.(string)
	}
	payload.Checks = checks

	return payload
}

func statusPageCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*updown.Client)

	page, _, err := client.StatusPage.Add(constructStatusPagePayload(d))
	if err != nil {
		return fmt.Errorf("creating status page with the API: %w", err)
	}

	d.SetId(page.Token)

	return statusPageRead(d, meta)
}

func statusPageRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*updown.Client)
	pages, _, err := client.StatusPage.List()

	if err != nil {
		return fmt.Errorf("reading status pages from the API: %w", err)
	}

	for _, p := range pages {
		if d.Id() == p.Token {
			for k, v := range map[string]interface{}{
				"name":        p.Name,
				"description": p.Description,
				"visibility":  p.Visibility,
				"access_key":  p.AccessKey,
				"url":         p.URL,
				"checks":      p.Checks,
			} {
				if err := d.Set(k, v); err != nil {
					return err
				}
			}
			return nil
		}
	}

	d.SetId("")
	return nil
}

func statusPageUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*updown.Client)

	_, _, err := client.StatusPage.Update(d.Id(), constructStatusPagePayload(d))
	if err != nil {
		return fmt.Errorf("updating status page with the API: %w", err)
	}

	return statusPageRead(d, meta)
}

func statusPageDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*updown.Client)
	deleted, _, err := client.StatusPage.Remove(d.Id())

	if err != nil {
		return fmt.Errorf("removing status page from the API: %w", err)
	}

	if !deleted {
		return fmt.Errorf("status page couldn't be deleted")
	}

	return nil
}

func statusPageExists(d *schema.ResourceData, meta interface{}) (bool, error) {
	err := statusPageRead(d, meta)
	return err == nil, err
}
